# Generated by Django 5.1.6 on 2025-03-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Roadmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=100)),
                ("roadmap_requirements", models.TextField()),
                (
                    "done_topics",
                    models.ManyToManyField(
                        blank=True, related_name="completed_roadmaps", to="api.topic"
                    ),
                ),
                (
                    "not_interested_topics",
                    models.ManyToManyField(
                        blank=True, related_name="skipped_roadmaps", to="api.topic"
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(related_name="roadmaps", to="api.topic"),
                ),
            ],
        ),
    ]
