# Generated by Django 5.1.6 on 2025-03-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roadmap",
            name="done_topics",
        ),
        migrations.RemoveField(
            model_name="roadmap",
            name="not_interested_topics",
        ),
        migrations.RemoveField(
            model_name="roadmap",
            name="topics",
        ),
    ]
