# Generated by Django 5.1.6 on 2025-03-01 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_resource"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Resource",
        ),
    ]
