# Generated by Django 5.1.6 on 2025-03-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_delete_resource"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="progress",
            field=models.IntegerField(default=0),
        ),
    ]
