# Generated by Django 5.1.6 on 2025-03-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_topic_progress"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topic",
            old_name="progress",
            new_name="completed_topics",
        ),
        migrations.AddField(
            model_name="topic",
            name="total_topics",
            field=models.IntegerField(default=0),
        ),
    ]
